all:
  children:
    servers:
      hosts:
        172.31.3.233:
          nopCommerce450_path: /var/www/nopCommerce450
          nopcommerce_zipfile: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.50.3/nopCommerce_4.50.3_NoSource_linux_x64.zip
          nginx_config_file_destination: /etc/nginx/sites-available/default
          