---
    - name: installing nodejs
      become: yes
      hosts: centos
      tasks:
        - name: Install nodejs
          ansible.builtin.yum:
            name: nodejs
            state: present
            update_cache: yes