---
- name:
  hosts: all
  become: yes
  tasks:
    - name: Upadate ubuntu packages and install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: start apache2 service
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        masked: no