---
    - name: installing nano
      become: yes
      hosts: all
      tasks:
        - name: Install nano
          ansible.builtin.apt:
            name: nano
            state: present
            update_cache: yes