# Manual steps for installing ha-proxy in ubuntu 20.04:
#------------------------------------------------------
    # 1  sudo apt update && sudo apt upgrade -y
    # 2  sudo apt install software-properties-common
    # 3  sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
    # 4  sudo apt update && sudo apt install haproxy -y
    # 5  sudo systemctl status haproxy
    # 6  sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg-org
    # 7  sudo vi /etc/haproxy/haproxy.cfg
    # 8  sudo systemctl restart haproxy
# ------------------------------------------------------------------------

---
- name: Installing Ha-Proxy in ubuntu
  become: yes
  hosts: all
  vars:
    Required_software_properties: software-properties-common
    apt_repository: ppa:vbernat/haproxy-2.6 
    Installing_package_name: haproxy
    Name_of_the_config_file: haproxy.cfg
    Default_Location_config_file: /etc/haproxy/haproxy.cfg
    Config_file_backup_location: /etc/haproxy/haproxy.cfg-org 
    Updated_config_file_location: /home/ansible/haproxy.config 
  tasks:
    - name: Using debug
      ansible.builtin.debug:
        msg: Upgrading Ubuntu packages and installing necessaty software properties
    - name: Updating packages 
      ansible.builtin.apt:
        name: "{{ Required_software_properties }}"
        update_cache: yes
        state: present
    - name: Using debug
      ansible.builtin.debug:
        msg: Downloading "{{ apt_repository }}" repo Using 'apt_repository' module    
    - name: Downloading "{{ apt_repository }}"
      ansible.builtin.apt_repository: 
        repo: "{{ apt_repository }}"
        state: present 
    - name: Using debug
      ansible.builtin.debug:
        msg: Installing 'haproxy' latest version
    - name: Installing haproxy
      ansible.builtin.apt:
        name: "{{ Installing_package_name }}" 
        update_cache: yes
        state: present
    - name: Using debug
      ansible.builtin.debug:
        msg: Copying "{{ Name_of_the_config_file }}" file from "{{ Default_Location_config_file }}" to  "{{ Config_file_backup_location }}" as a backup
    - name: Copying 'haproxy.cfg' file for backup
      ansible.builtin.copy:
        src: "{{ Default_Location_config_file }}"
        dest: "{{ Config_file_backup_location }}"
        remote_src: yes    
      notify:
        - Restarting haproxy
    - name: Using debug
      ansible.builtin.debug:
        msg: Adding 'nodes' to load balancer the nodes from haproxy server
    - name: Adding nodes
      ansible.builtin.copy:
        src: "{{ Updated_config_file_location }}"
        dest: "{{ Default_Location_config_file }}"
      notify:
        - Restarting haproxy  
    - name: Using debug
      ansible.builtin.debug:
        msg: Restarting haproxy service
  handlers:      
    - name: Restarting haproxy
      ansible.builtin.systemd:
        name: "{{ Installing_package_name }}"
        daemon_reload: yes
        enabled: yes
        state: restarted
                                


