--- 
- name: Running Jenkins as a service
  hosts: all 
  become: yes
  tasks:
    - name: Using debug 
      ansible.builtin.debug:
        msg: installing openjdk 11 
    - name: Installing java 11
      ansible.builtin.yum:
        name: java-11-openjdk-devel
        state: present 
        update_cache: yes
    - name: Using debug 
      ansible.builtin.debug:
        msg: Downloading jenkins war file from 'https://updates.jenkins.io/download/war/2.385/jenkins.war'
    - name: Downloading jenkins war file 
      ansible.builtin.get_url:
        url: https://updates.jenkins.io/download/war/2.385/jenkins.war   
        dest: /home/ansible
    - name: Using debug
      ansible.builtin.debug:
        msg: Adding service file for jenkins to make it as a service
    - name: adding jenkins service file
      ansible.builtin.copy:
        src: ./jenkins2.service
        dest: /lib/systemd/system/jenkins.service
    - name: Using debug
      ansible.builtin.debug:
        msg: Starting jenkins service
    - name: Starting jenkins
      ansible.builtin.systemd:
        name: jenkins
        daemon_reload: yes
        enabled: yes
        state: started                        
    - name: Using debug
      ansible.builtin.debug:
        msg: Restarting jenkins service
      notify:
        - Restarting jenkins  
  handlers:      
    - name: Restarting jenkins
      ansible.builtin.service:
        name: jenkins
        enabled: yes
        state: restarted    