all:
  children:
    jboss:
      hosts:
      # ubuntu
        172.31.84.209:
          java_package_name: openjdk-11-jdk
      # centos    
        172.31.80.173:
          java_package_name: java-11-openjdk-devel
          
            
            