---
  - name: installing wildfly
    become: yes
    hosts: all
    tasks:
      - name: installing java apt
        ansible.builtin.apt:
          name:  openjdk-11-jdk
          update_cache: yes
          state: present
      - name:  wildfly
        ansible.builtin.group:
          name:  wildfly
          state: present
      - name: creating a user
        ansible.builtin.user:
          name: wildfly
          group: wildfly
          system: yes
          shell: sbin/nologin
          create_home: yes
          home: /opt/wildfly
      - name: Create a directory if it does not exist
        ansible.builtin.file:
          path: /opt
          state: directory
      - name: getting url from website
        ansible.builtin.get_url:
          url: https://download.jboss.org/wildfly/22.0.1.Final/wildfly-22.0.1.Final.tar.gz
          dest: /wildfly-27.0.1.Final.tar.gz
      - name: extracting a zip file
        ansible.builtin.unarchive:
          src: /wildfly-27.0.1.Final.tar.gz
          dest: /opt/wildfly
          remote_src: yes
      # - name: Create a symbolic link
      #   ansible.builtin.file:
      #     src: /opt/wildfly-27.0.1.Final
      #     dest: /opt/wildfly
      #     owner: wildfly
      #     group: wildfly
      #     state: link
      - name: moving folder to /opt/wildfly
        ansible.builtin.copy:
          src: /opt/wildfly-27.0.1.Final/
          dest: /opt/wildfly
          owner: wildfly
          group: wildfly
          mode: '777'
          remote_src: yes
      - name: Recursively change ownership of a directory
        ansible.builtin.file:
          path: /opt/wildfly
          state: directory
          recurse: yes
          owner: wildfly
          group: wildfly
      - name: creating directory
        ansible.builtin.file:
          path: /etc/wildfly
          state: directory
      - name: copying file to /etc/wildfly
        ansible.builtin.copy:
          src: /opt/wildfly-27.0.1.Final/docs/contrib/scripts/systemd/wildfly.conf
          dest: /etc/wildfly/
          owner: wildfly
          group: wildfly
          remote_src: yes
      - name: copying file to /etc/wildfly
        ansible.builtin.copy:
          src: /opt/wildfly-27.0.1.Final/docs/contrib/scripts/systemd/launch.sh
          dest: /opt/wildfly/bin/
          owner: wildfly
          group: wildfly
          remote_src: yes
      - name: Touch the same file, but add/remove some permissions
        ansible.builtin.file:
            path: /opt/tomcat/updated/bin/*.sh
            state: touch
            mode: u+x+w
      - name: copying file to /etc/wildfly
        ansible.builtin.copy:
          src: /opt/wildfly-27.0.1.Final/docs/contrib/scripts/systemd/wildfly.service
          dest: /etc/systemd/system/
          owner: wildfly
          group: wildfly
          remote_src: yes
      - name: Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
        ansible.builtin.systemd:
          state: restarted
          daemon_reload: yes
          name: wildfly
      - name: Restart service 
        ansible.builtin.service:
          name: wildfly
          state: started